name: Run tests

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0
      - name: Run tests
        run: npm test
